/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  RX63N_LedButton                        */
/*      FILE         :  RX63N_LedButton.c                      */
/*      DESCRIPTION  :  Main Program                           */
/*                                                             */
/*      This file was generated by e2 studio.                  */
/*                                                             */
/***************************************************************/

#include "iodefine.h"
#include <stdint.h>
#include "bss.h"
#ifdef CPPAPP
//Initialize global constructors
extern void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif


static inline __attribute__((always_inline))void delay(void){
	for(uint32_t j= 0; j < 1000; j++);
}

int main(void) {
	BSS_Init();
    while(1) {
    	for(uint8_t i = 0; i < 8; i++){
    		LED(i, LED_ON);
    		delay();
    		LED(i, LED_OFF);
    		delay();
    	}
	// TODO: add application code here
    }
return 0;
}
